TOOLS_JSON_FILE = 'tools.json'
PATHS_JSON_FILE = 'paths.json'
HM_PKGS_DIR = 'resources'
TOOLS_DIR = 'installed_tools'
RES_ROOT_DIR = 'huntsman_results'
SUB_MASTER_FILE = 'subdomains.all'
ENDP_MASTER_FILE = 'endpoints.all'